# Generated by Django 2.1.2 on 2018-11-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name': 'Input',
                'verbose_name_plural': 'Inputs',
            },
        ),
    ]
